---
resources:
  - name: test_repository
    type: git
    source:
      uri: 
      branch: master

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: test_repository
      - task:
          name: hello-world
          file: ./test_pipeline/tasks/hello-world.yml